services:
  headscale-admin:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    image: goodieshq/headscale-admin:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
